version: '3'
services:
  container1:
    build:
      context: ./container-a
    ports:
      - "2222:22"
    networks:
      - ctf_network

  container2:
    build:
      context: ./container-b
    ports:
      - "2223:22"
    depends_on:
      - container1
    networks:
      - ctf_network

  container3:
    build:
      context: ./container-c
    ports:
      - "5000:5000"
    depends_on:
      - container2
    networks:
      - ctf_network

networks:
  ctf_network:
    driver: bridge
