version: '3'
services:
  container1:
    build:
      context: ./con-start
    ports:
      - "2222:22"
    networks:
      - ctf_network
    volumes:
      - shared:/shared

  container2:
    build:
      context: ./con-server
    ports:
      - "5000:5000"
    networks:
      - ctf_network
    volumes:
      - shared:/shared

  container3:
    build:
      context: ./con-bof
    ports:
      - "2223:22"
    networks:
      - ctf_network
    volumes:
      - shared:/shared

networks:
  ctf_network:
    driver: bridge
volumes:
  shared:
